### ISSUE TITLE
value column returned by list_to_df() is a list

### ISSUE THREAD

**Issue by jtr13** [krlmlr/kimisc#11]
> x <- list(a = 1, b = 2, c = 3)
    > y <- list_to_df(x)
    > y
      name value
    1    a     1
    2    b     2
    3    c     3
Looks ok, but...

    > str(y)
    'data.frame':	3 obs. of  2 variables:
     $ name : chr  "a" "b" "c"
     $ value:List of 3
      ..$ : num 1
      ..$ : num 2
      ..$ : num 3

**Comment by jtr13** [comment]
Looks like `tidyr::unnest()` will solve it:

```
> y <- list_to_df(x) %>% unnest()
> str(y)
'data.frame':	3 obs. of  2 variables:
 $ name : chr  "a" "b" "c"
 $ value: num  1 2 3
```

**Comment by krlmlr** [comment]
I have deprecated `list_to_df()`, please use `tibble::enframe()`.
