### ISSUE TITLE
Feature request: could format_fun support a purrr style lambda? 

### ISSUE THREAD

**Issue by davidhodge931** [krlmlr/kimisc#13]
Thanks for the useful `cut_format` function!

Is it possible that the `format_fun` argument in `cut_format` could support a purrr style lambda?

```
library(kimisc)
#this works
cut_format(runif(10), seq(0, 1, by = 0.25), 
           format_fun = function(x) paste(x * 100, "%"))

#this doesn't, but it'd be great if it did
cut_format(runif(10), seq(0, 1, by = 0.25), 
           format_fun = ~ paste(.x * 100, "%"))
```

**Comment by krlmlr** [comment]
Thanks. The excellent {santoku} package is dedicated to binning, it might support what you're looking for. (`?cut_format` should really point there too.)

**Comment by davidhodge931** [comment]
Oh I hadn't seen that package, thanks!

Just to check, is kimisc::cut_format going to stick around?

I've built a package on CRAN that currently has it as a dependency

**Comment by davidhodge931** [comment]
I've moved to using  {santoku} instead - thanks!
